version: "3.8"
services:
  redis:
    image: redis:alpine
    command: redis-server
    expose:
      - 6379
    volumes:
      - redis:/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
volumes:
  redis:
